{% set name = "dlclibrary" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96a589f8bb79f499ecfd1156f751c693dd184e09c06afa69af31bb9c07900cf8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - huggingface_hub
    - ruamel.yaml >=0.17.21

test:
  imports:
    - dlclibrary
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/DeepLabCut/dlclibrary
  summary: DLClibrary is a lightweight library supporting universal functions for the DeepLabCut ecosystem.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
