{% set name = "dlclibrary" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b4ca078dc9cddb2a1f30d42cbc9d5c0e849e0f93f2b6781ca478baed0a829b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - huggingface_hub
    - ruamel.yaml

test:
  imports:
    - dlclibrary
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DeepLabCut/dlclibrary
  summary: DLClibrary is a lightweight library supporting universal functions for the DeepLabCut ecosystem.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
