{% set version = "0.0.11" %}

package:
  name: dlclibrary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dlclibrary/dlclibrary-{{ version }}.tar.gz
  sha256: 2483a8c2c0cefb1c6defd1c4afd0095bf9bd956204241d102231101f08f21d98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - huggingface_hub >=0.11.1
    - ruamel.yaml >=0.17.21

test:
  imports:
    - dlclibrary
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/DeepLabCut/dlclibrary
  summary: DLClibrary is a lightweight library supporting universal functions for the DeepLabCut ecosystem.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
