{% set name = "dlclibrary" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 321303ae8b54b00fc79431d14b68f5c55a77989b57fa1ad71a1ed254c1794ded

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - huggingface_hub
    - ruamel.yaml >=0.15.0

test:
  imports:
    - dlclibrary
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DeepLabCut/dlclibrary
  summary: DLClibrary is a lightweight library supporting universal functions for the DeepLabCut ecosystem.
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
